steps:
  # Step 1: Checkout the source code repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/mayo8624/GCP-DEMO.git']
    dir: 'workspace'  # Adjust this according to your directory structure

  - name: 'timvancann/databricks-cli'  # Use the official Cloud Build Databricks installer image
    # args: ['--version', 'latest']  # Optional: Specify a Databricks CLI version (defaults to latest)

  # Step 3: Deploy notebooks to Databricks workspace
  - name: 'Run Databricks CLI commands'
  args: ['--']  # Separate build commands from container entrypoint
  # Replace these commands with your specific Databricks notebook deployment tasks
  # (e.g., login, cluster creation, notebook execution, etc.)
  command: [
      'bash', '-c', '
        # Login to Databricks (replace with your credentials)
        databricks configure --token dapicd225a3be886969133e88a58e9afe2bd-3
        
        # Specific notebook deployment commands (replace with your commands)
        # databricks notebooks publish --overwrite --path /path/to/your/notebook.dbc /Users/<your-username>/<notebook-name>.dbc
        
        # Additional Databricks CLI commands as needed
      '
  ]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
