steps:
  # Step 1: Checkout the source code repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/mayo8624/GCP-DEMO.git']
    dir: 'workspace'  # Adjust this according to your directory structure

  - name: 'timvancann/databricks-cli'  # Use the official Cloud Build Databricks installer image
    # args: ['--version', 'latest']  # Optional: Specify a Databricks CLI version (defaults to latest)

  # Step 3: Deploy notebooks to Databricks workspace
  - name: 'timvancann/databricks-cli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set Databricks Host
        export DATABRICKS_HOST="https://adb-1499785588441012.12.azuredatabricks.net"
        # Login to Databricks using token
        databricks configure --token
        # Enter your token when prompted
        echo "dapicd225a3be886969133e88a58e9afe2bd-3"
        
        # Specific notebook deployment commands (replace with your commands)
        databricks notebooks publish --overwrite --path abc/notebook.dbc /Users/mayo8624/Gold.py
        
        # Additional Databricks CLI commands as needed
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
