# steps:
#   - name: 'gcr.io/cloud-builders/echo'
#     args:
#       - 'Hello, Cloud Build!'
# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "enter 1 bash command per line"
          ls -la
          gcloud version
          ...
