steps:
  # Step 1: Checkout the source code repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/mayo8624/GCP-DEMO.git']
    dir: 'workspace'  # Adjust this according to your directory structure

# Step 2: (Optional) Install Databricks CLI
# - name: 'gcr.io/cloud-builders/install/databricks'
#   args: ['--version', 'latest']  # Optional: Specify a Databricks CLI version (defaults to latest)

# Step 3: Deploy notebooks to Databricks workspace
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Authenticate Databricks CLI
      echo dapicd225a3be886969133e88a58e9afe2bd-3 | databricks configure --token
      
      # Loop through notebooks and deploy to Databricks workspace
      # for notebook in workspace/notebooks/*.ipynb; do
      #   databricks workspace import -f IPYNB "$notebook" /<path_in_databricks_workspace>/
      # done

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

