name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed
    
      
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
        
      - name: Configure Databricks CLI
        run: |
           databricks configure --token "${{ secrets.DATABRICKS_TOKEN }}" --host "${{ secrets.DATABRICKS_HOST }}"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      - name: Clone GitHub Repository
        run: |
          git clone https://github.com/mayo8624/GCP-DEMO.git
          cd GCP-DEMO
        # Navigate to the cloned repository directory
      - name: Import Notebooks to Databricks
        run: |
          target_folder="/live"
          # Define the target Databricks folder
          # Find all Python notebooks in the repository and import them one by one
          find . -name '*.py' | while IFS= read -r notebook_file; do
            notebook_name=$(basename "$notebook_file")
            echo "Importing $notebook_name to Databricks folder: $target_folder"
            databricks workspace import --language PYTHON --format SOURCE --file "$notebook_file" "$target_folder/$notebook_name"
          done
        shell: bash
      # - name: Import Notebooks to Databricks
      #   run: |
      #     target_folder="/live"
      #     # Define the target Databricks folder
      #     # Iterate through all Python notebooks in the repository and import them
      #     find . -name '*.py' | while read notebook_file; do
      #       notebook_name=$(basename "$notebook_file")
      #       echo "Importing $notebook_name to Databricks folder: $target_folder"
      #       databricks workspace import --language PYTHON --format SOURCE --file "$notebook_file" "$target_folder/$notebook_name"
      #     done

          
      # - name: Import gold.py to Databricks
      #   run: |
      #       databricks workspace import --language PYTHON --format SOURCE --file Gold.py /live/gold
      #      # databricks workspace import --language PYTHON /gold2.py
      #     # databricks workspace import --language PYTHON gold.py /workspace/live
      # - name: Import notebooks to Databricks
      #   run: |
      #     # Iterate through notebooks in the repository
      #      for notebook_file in $(find . -name '*.py'); do
      #        databricks workspace import --format SOURCE --language PYTHON --overwrite --file "$notebook_file" "${{ env.DATABRICKS_WORKSPACE_PATH }}"
      #      done
        
        env:
          DATABRICKS_WORKSPACE_PATH: /Users/prathamesh.bhamare@celebaltech.com/abcd2  # Replace with your desired Databricks workspace path
