name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed
      - name: Databricks Deploy
        uses: antstackio/databricks-deploy@v1.0.4
        with:
    # Hostname of the Databricks workspace in which to deploy the latest code. If unspecified, the hostname will be inferred from the DATABRICKS_HOST environment variable. Either this parameter or the DATABRICKS_HOST environment variable must be set.
           databricks-host: ${{ secrets.DATABRICKS_HOST }}
    # Repo Id of the Databricks repo. If unspecified, the repo-id will be inferred from the DATABRICKS_REPO_ID environment variable.  Either this parameter or the DATABRICKS_REPO_ID environment variable must be set.
           databricks-repo-id: https://github.com/mayo8624/GCP-DEMO.git
    # The branch of the Databricks repo-id mentioned above. This action will update the mentioned branch.
           databricks-repo-branch: main 
           databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
      
      # - name: Install Databricks CLI
      #   uses: microsoft/install-databricks-cli@v1.0.0
        
      # - name: Configure Databricks CLI
      #   run: |
      #     databricks configure --token "${{ secrets.DATABRICKS_HOST }}"
      #     # echo $DATABRICKS_TOKEN | databricks configure --token
      #     # echo $DATABRICKS_HOST | databricks configure --host 
      #   env:
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

      # - name: Import notebooks to Databricks
      #   run: |
      #     # Iterate through notebooks in the repository
      #     find . -name '*.py' | while read notebook_file; do
      #       databricks workspace import -o --language PYTHON "$notebook_file" "${{ env.DATABRICKS_WORKSPACE_PATH }}"
      #     done
      #   env:
      #     DATABRICKS_WORKSPACE_PATH: /Users/prathamesh.bhamare@celebaltech.com/imported_notebooks  # Replace with your desired Databricks workspace path
