name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed
    
      
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main
        
      - name: Configure Databricks CLI
        run: |
           databricks configure --token "${{ secrets.DATABRICKS_TOKEN }}" --host "${{ secrets.DATABRICKS_HOST }}"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      - name: Clone GitHub Repository
        run: |
          git clone https://github.com/mayo8624/GCP-DEMO.git
        # Navigate to the cloned repository directory

      # - name: Import gold.py to Databricks
         # run: |
          # databricks workspace import --language PYTHON /gold.py
          # databricks workspace import --language PYTHON gold.py /workspace/live
      - name: Import notebooks to Databricks
        run: |
          # Iterate through notebooks in the repository
          # for notebook_file in $(find . -name '*.py'); do
             databricks workspace import --format SOURCE --language PYTHON --overwrite --file "*.py" "${{ env.DATABRICKS_WORKSPACE_PATH }}"
          # done
        env:
          DATABRICKS_WORKSPACE_PATH: /Users/prathamesh.bhamare@celebaltech.com/imported_notebooks  # Replace with your desired Databricks workspace path
