name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure Python 3.x is installed

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          /home/runner/.local/bin/databricks configure --token
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

      - name: Import notebooks to Databricks
        run: |
          # Iterate through notebooks in the repository
          find . -name '*.py' | while read notebook_file; do
            databricks workspace import -o --language PYTHON "$notebook_file" "${{ env.DATABRICKS_WORKSPACE_PATH }}"
          done
        env:
          DATABRICKS_WORKSPACE_PATH: /Users/prathamesh.bhamare@celebaltech.com/imported_notebooks  # Replace with your desired Databricks workspace path
